
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Spring setting
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#http://localhost:8080/h2-console
spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
logging:
  level:
    org.hibernate.type: trace
server:
  port:
    8080
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:sql/h2/schema.sql
#---
#spring:
#  profiles: local
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    #    initialization-mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

